version: '3.8'
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true